# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
   
    
    - name: checkout
      uses: actions/checkout@v2
    - name: latest GA markdown
      uses: enflo/curl-action@v1.2
      with:
        curl: --output changelog.md https://8985076f23d7.ngrok.io/swagger/diff?markdown 
    
    - name: latest Beta markdown
      uses: enflo/curl-action@v1.2
      with:
      # curl arguments
        curl: --output changelog-beta.md https://8985076f23d7.ngrok.io/swagger/diff?markdown&latestBeta
   
    - name: Commit files # commit the output folder
      run: |
        git config --local user.email "cguynn@gmail.com"
        git config --local user.name "dexterlabora"
        git add .
        git commit -m "update changelog"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     - name: changelog
#       uses: satak/webrequest-action@master
#       with:
#         url: https://us-central1-focal-rig-261016.cloudfunctions.net/app/swagger/diff
#         method: POST
#         payload: '{"oldSpec": "https://raw.githubusercontent.com/meraki/openapi/v0.9.0/openapi/spec2.json","newSpec": "https://raw.githubusercontent.com/meraki/openapi/v1.0.0-beta.0/openapi/spec2.json"}'
#         run: |
#           $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
#           Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"
